2020-06-12 08:55:19,240 ERROR: Exception on /auth/reset_password_request [POST] [in c:\python\python37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\python\python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Flask\microblog\app\auth\routes.py", line 88, in reset_password_request
    send_password_reset_email(user)
  File "E:\Flask\microblog\app\auth\email.py", line 17, in send_password_reset_email
    html_body='this is html body ' + [user.email])
TypeError: can only concatenate str (not "list") to str
2020-06-12 08:56:38,686 INFO: Microblog startup [in E:\Flask\microblog\app\__init__.py:85]
2020-06-12 08:56:53,811 ERROR: Exception on /auth/reset_password_request [POST] [in c:\python\python37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\python\python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Flask\microblog\app\auth\routes.py", line 88, in reset_password_request
    send_password_reset_email(user)
  File "E:\Flask\microblog\app\auth\email.py", line 17, in send_password_reset_email
    html_body= [user.email])
  File "E:\Flask\microblog\app\email.py", line 14, in send_email
    mail.send(msg)
  File "c:\python\python37\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "c:\python\python37\lib\site-packages\flask_mail.py", line 427, in send
    connection.send(self)
  File "c:\python\python37\lib\site-packages\flask_mail.py", line 190, in send
    message.as_bytes() if PY3 else message.as_string(),
  File "c:\python\python37\lib\site-packages\flask_mail.py", line 385, in as_bytes
    return self._message().as_bytes()
  File "c:\python\python37\lib\email\message.py", line 178, in as_bytes
    g.flatten(self, unixfrom=unixfrom)
  File "c:\python\python37\lib\email\generator.py", line 116, in flatten
    self._write(msg)
  File "c:\python\python37\lib\email\generator.py", line 181, in _write
    self._dispatch(msg)
  File "c:\python\python37\lib\email\generator.py", line 214, in _dispatch
    meth(msg)
  File "c:\python\python37\lib\email\generator.py", line 272, in _handle_multipart
    g.flatten(part, unixfrom=False, linesep=self._NL)
  File "c:\python\python37\lib\email\generator.py", line 116, in flatten
    self._write(msg)
  File "c:\python\python37\lib\email\generator.py", line 181, in _write
    self._dispatch(msg)
  File "c:\python\python37\lib\email\generator.py", line 214, in _dispatch
    meth(msg)
  File "c:\python\python37\lib\email\generator.py", line 272, in _handle_multipart
    g.flatten(part, unixfrom=False, linesep=self._NL)
  File "c:\python\python37\lib\email\generator.py", line 116, in flatten
    self._write(msg)
  File "c:\python\python37\lib\email\generator.py", line 181, in _write
    self._dispatch(msg)
  File "c:\python\python37\lib\email\generator.py", line 214, in _dispatch
    meth(msg)
  File "c:\python\python37\lib\email\generator.py", line 427, in _handle_text
    if _has_surrogates(msg._payload) and not self.policy.cte_type=='7bit':
  File "c:\python\python37\lib\email\utils.py", line 57, in _has_surrogates
    s.encode()
AttributeError: 'list' object has no attribute 'encode'
2020-06-12 08:58:42,407 INFO: Microblog startup [in E:\Flask\microblog\app\__init__.py:85]
2020-06-12 08:58:57,666 ERROR: Exception on /auth/reset_password_request [POST] [in c:\python\python37\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\python\python37\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\python37\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Flask\microblog\app\auth\routes.py", line 88, in reset_password_request
    send_password_reset_email(user)
  File "E:\Flask\microblog\app\auth\email.py", line 18, in send_password_reset_email
    html_body= [user.email])
  File "E:\Flask\microblog\app\email.py", line 14, in send_email
    mail.send(msg)
  File "c:\python\python37\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "c:\python\python37\lib\site-packages\flask_mail.py", line 427, in send
    connection.send(self)
  File "c:\python\python37\lib\site-packages\flask_mail.py", line 190, in send
    message.as_bytes() if PY3 else message.as_string(),
  File "c:\python\python37\lib\site-packages\flask_mail.py", line 385, in as_bytes
    return self._message().as_bytes()
  File "c:\python\python37\lib\email\message.py", line 178, in as_bytes
    g.flatten(self, unixfrom=unixfrom)
  File "c:\python\python37\lib\email\generator.py", line 116, in flatten
    self._write(msg)
  File "c:\python\python37\lib\email\generator.py", line 181, in _write
    self._dispatch(msg)
  File "c:\python\python37\lib\email\generator.py", line 214, in _dispatch
    meth(msg)
  File "c:\python\python37\lib\email\generator.py", line 272, in _handle_multipart
    g.flatten(part, unixfrom=False, linesep=self._NL)
  File "c:\python\python37\lib\email\generator.py", line 116, in flatten
    self._write(msg)
  File "c:\python\python37\lib\email\generator.py", line 181, in _write
    self._dispatch(msg)
  File "c:\python\python37\lib\email\generator.py", line 214, in _dispatch
    meth(msg)
  File "c:\python\python37\lib\email\generator.py", line 272, in _handle_multipart
    g.flatten(part, unixfrom=False, linesep=self._NL)
  File "c:\python\python37\lib\email\generator.py", line 116, in flatten
    self._write(msg)
  File "c:\python\python37\lib\email\generator.py", line 181, in _write
    self._dispatch(msg)
  File "c:\python\python37\lib\email\generator.py", line 214, in _dispatch
    meth(msg)
  File "c:\python\python37\lib\email\generator.py", line 427, in _handle_text
    if _has_surrogates(msg._payload) and not self.policy.cte_type=='7bit':
  File "c:\python\python37\lib\email\utils.py", line 57, in _has_surrogates
    s.encode()
AttributeError: 'list' object has no attribute 'encode'
2020-06-12 09:00:03,035 INFO: Microblog startup [in E:\Flask\microblog\app\__init__.py:85]
2020-06-12 09:02:30,580 INFO: Microblog startup [in E:\Flask\microblog\app\__init__.py:85]
2020-06-12 09:04:48,429 INFO: Microblog startup [in E:\Flask\microblog\app\__init__.py:85]
2020-06-12 09:06:43,287 INFO: Microblog startup [in E:\Flask\microblog\app\__init__.py:85]
